//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfAppMaterialDesign
{
    using System;
    using System.Collections.Generic;
    
    public partial class Call
    {
        public System.DateTime Дата_и_время { get; set; }
        public int Длительность { get; set; }
        public decimal Стоимость { get; set; }
        public int Номер_договора_FK { get; set; }
        public int Код_типа_звонка_FK { get; set; }
    
        public virtual Dogovor Dogovor { get; set; }
        public virtual Тип_звонка Тип_звонка { get; set; }
    }
}
