//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfAppMaterialDesign
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dogovor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dogovor()
        {
            this.Call = new HashSet<Call>();
        }
    
        public System.DateTime Дата_заключения { get; set; }
        public int Номер_договора { get; set; }
        public string Номер_телефона { get; set; }
        public string Серийный_номер_сим_карты { get; set; }
        public Nullable<System.DateTime> Дата_расторжения { get; set; }
        public int Код_тарифа_FK { get; set; }
        public int Номер_клиента_FK { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Call> Call { get; set; }
        public virtual Клиент Клиент { get; set; }
        public virtual Тариф Тариф { get; set; }
    }
}
