//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfAppMaterialDesign
{
    using System;
    using System.Collections.Generic;
    
    public partial class Тариф
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Тариф()
        {
            this.Dogovor = new HashSet<Dogovor>();
        }
    
        public Nullable<decimal> Минута_межгород_стоимость { get; set; }
        public decimal Минута_международная_стоимость { get; set; }
        public string Название_тарифа { get; set; }
        public decimal Стоимость_перехода { get; set; }
        public int Код_типа_тарифа_FK { get; set; }
        public int Код_тарифа { get; set; }
        public Nullable<int> Год_начала { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dogovor> Dogovor { get; set; }
        public virtual Тип_тарифа Тип_тарифа { get; set; }
    }
}
